plugin:
  name: gitops-enhanced
  image: quay.io/gitops-enhanced/gitops-enhanced-plugin:latest
  replicas: 1
  port: 9443
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

argocd:
  namespace: openshift-gitops
  serviceName: openshift-gitops-server
  port: 443
