plugin:
  name: gitops-enhanced
  image: image-registry.openshift-image-registry.svc:5000/gitops-enhanced-plugin/gitops-enhanced-plugin:latest
  replicas: 1
  port: 9443
  resources:
    requests:
      cpu: 1m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

argocd:
  namespace: openshift-gitops
  serviceName: openshift-gitops-server
  port: 443
